import "../dist/style.css";
import { Noto_Sans } from "next/font/google";
import { Header } from "@/components/header/Header";
import { Footer } from "@/components/footer/Footer";

const notoSans = Noto_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--notoSans-font",
});

export const metadata = {
  title: "Smart Door",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${notoSans.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
